<?php

namespace BluesoftBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractRepository extends EntityRepository
{
    public function findContractsForPresentation()
    {
        $result = $this->getEntityManager()
                       ->createQueryBuilder()
                       ->select('c', 's')
                       ->from('BluesoftBundle:Contract', 'c')
                       ->leftJoin('c.system', 's')
                       ->getQuery()
                       ->getResult();

        if (!$result)
            return [];

        return $result;
    }

}
