services:
    xls.validator:
        class: BluesoftBundle\Service\XlsUtilities\XlsValidator

    xls.data.validator:
        class: BluesoftBundle\Service\XlsUtilities\XlsDataValidator
        arguments: ["@service_container"]

    xls.agent:
        class: BluesoftBundle\Service\XlsUtilities\XlsAgent
        arguments: ["@service_container", "@xls.validator"]

    xls.data.presenter:
        class: BluesoftBundle\Service\DataPresenter\XlsDataPresenter
        arguments: ["@service_container"]
